sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  slack: norch:wLsHiXjnAH5BdtTq3qtAqGp7
  email: false
node_js:
  - '8'
  - '6'
  - '4'
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
